log_level = "info"
max_concurrent_tasks = 32

listen_address = "0.0.0.0:8443"

auth_key = "./assets/example-certs/server/server.key"
auth_cert = "./assets/example-certs/server/server.crt"

# trusted client CAs
client_ca = "./assets/example-certs/ca.crt"
quic = true
